/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface TelephoneSolutionInterface extends utils.Interface {
  functions: {
    "en()": FunctionFragment;
    "tryit()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "en" | "tryit"): FunctionFragment;

  encodeFunctionData(functionFragment: "en", values?: undefined): string;
  encodeFunctionData(functionFragment: "tryit", values?: undefined): string;

  decodeFunctionResult(functionFragment: "en", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tryit", data: BytesLike): Result;

  events: {};
}

export interface TelephoneSolution extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TelephoneSolutionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    en(overrides?: CallOverrides): Promise<[string]>;

    tryit(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  en(overrides?: CallOverrides): Promise<string>;

  tryit(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    en(overrides?: CallOverrides): Promise<string>;

    tryit(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    en(overrides?: CallOverrides): Promise<BigNumber>;

    tryit(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    en(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tryit(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
